/** Curated set of airline and booking platform sender domains for O(1) lookup */
export const AIRLINE_DOMAINS: Set<string> = new Set([
  // --- US Major Airlines ---
  'united.com',
  'aa.com',
  'delta.com',
  'southwest.com',
  'jetblue.com',
  'alaskaair.com',
  'spirit.com',
  'frontierairlines.com',
  'allegiantair.com',
  'hawaiianairlines.com',
  'suncountry.com',
  'breezeairways.com',
  'avelo.com',

  // --- Canadian Airlines ---
  'aircanada.com',
  'westjet.com',
  'porterairlines.com',
  'flairair.com',

  // --- European Airlines ---
  'britishairways.com',
  'lufthansa.com',
  'airfrance.com',
  'klm.com',
  'iberia.com',
  'vueling.com',
  'ryanair.com',
  'easyjet.com',
  'wizz.com',
  'wizzair.com',
  'norwegian.com',
  'sas.dk',
  'flysas.com',
  'finnair.com',
  'icelandair.com',
  'brusselsairlines.com',
  'austrian.com',
  'swiss.com',
  'eurowings.com',
  'aeroflot.com',
  'turkishairlines.com',
  'thy.com',
  'aegeanair.com',
  'tapportugal.com',
  'alitalia.com',
  'ita-airways.com',
  'lot.com',
  'csaair.com',
  'tarom.ro',
  'airbaltic.com',
  'transavia.com',
  'volotea.com',
  'condor.com',
  'tuifly.com',
  'airmalta.com',
  'luxair.lu',
  'airserbia.com',
  'croatiaairlines.com',
  'pegasus.com',
  'flypgs.com',
  'sundair.com',

  // --- Middle East Airlines ---
  'emirates.com',
  'etihad.com',
  'qatarairways.com',
  'saudia.com',
  'gulfair.com',
  'omanair.com',
  'royaljordanian.com',
  'flydubai.com',
  'flynas.com',
  'jazeera.com',

  // --- Asian Airlines ---
  'singaporeair.com',
  'cathaypacific.com',
  'ana.co.jp',
  'jal.co.jp',
  'koreanair.com',
  'asiana.com',
  'thaiairways.com',
  'vietnamairlines.com',
  'philippineairlines.com',
  'cebupacificair.com',
  'airasia.com',
  'scoot.com',
  'tigerair.com',
  'jetstar.com',
  'airchina.com',
  'csair.com',
  'ceair.com',
  'hainanairlines.com',
  'xiamenair.com',
  'shenzhenair.com',
  'juneyaoair.com',
  'springairlines.com',
  'evaair.com',
  'starlux-airlines.com',
  'tigerairtw.com',
  'airindia.com',
  'goindigo.in',
  'spicejet.com',
  'airvistara.com',
  'goair.in',
  'flybigair.com',
  'silkair.com',
  'batikair.com',
  'garudaindonesia.com',
  'lionair.co.id',
  'citilink.co.id',
  'malaysiaairlines.com',
  'fireflyz.com',
  'mongolianairlines.com',
  'drukair.com',
  'srilankan.com',
  'himalaya-airlines.com',

  // --- Oceania Airlines ---
  'qantas.com',
  'virginaustralia.com',
  'airnewzealand.co.nz',
  'fijiairways.com',
  'aircalin.com',

  // --- Latin American Airlines ---
  'latam.com',
  'avianca.com',
  'copaair.com',
  'aeromexico.com',
  'volaris.com',
  'vivaaerobus.com',
  'azul.com.br',
  'voegol.com.br',
  'jetsmart.com',
  'flyarajet.com',
  'wingo.com',
  'interjet.com',

  // --- African Airlines ---
  'ethiopianairlines.com',
  'egyptair.com',
  'royalairmaroc.com',
  'southafricanairways.com',
  'flysafair.co.za',
  'kenya-airways.com',
  'rwandair.com',
  'airalgerie.dz',
  'tunisair.com',
  'arikair.com',
  'flyairpeace.com',
  'fastjet.com',

  // --- Booking Platforms ---
  'expedia.com',
  'kayak.com',
  'booking.com',
  'priceline.com',
  'skyscanner.com',
  'skyscanner.net',
  'google.com',
  'orbitz.com',
  'travelocity.com',
  'cheapflights.com',
  'momondo.com',
  'hopper.com',
  'kiwi.com',
  'trip.com',
  'ctrip.com',
  'makemytrip.com',
  'cleartrip.com',
  'yatra.com',
  'ixigo.com',
  'goibibo.com',
  'despegar.com',
  'edreams.com',
  'opodo.com',
  'lastminute.com',
  'flyertalk.com',
  'skiplagged.com',
  'secretflying.com',
  'scottscheapflights.com',
  'going.com',
  'farecompare.com',
  'airfarewatchdog.com',
  'studentuniverse.com',
  'flightaware.com',
  'flightradar24.com',

  // --- Travel Agencies / Corporate ---
  'amexgbt.com',
  'bcdtravel.com',
  'cwt.com',
  'travelperk.com',
  'navan.com',
  'tripactions.com',
  'concur.com',
  'egencia.com',
  'travelport.com',
  'sabre.com',
  'amadeus.com',

  // --- Credit Card Travel ---
  'chase.com',
  'americanexpress.com',
  'capitalone.com',
  'citi.com',

  // --- Loyalty / Miles ---
  'mileageplus.com',
  'aadvantage.com',
  'rapidrewards.com',
  'points.com',
  'awardwallet.com',
])

export function isAirlineDomain(domain: string): boolean {
  return AIRLINE_DOMAINS.has(domain.toLowerCase())
}
